//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Cerveza
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CERVECERIA_CLLEntities : DbContext
    {
        public CERVECERIA_CLLEntities()
            : base("name=CERVECERIA_CLLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_Cliente> TB_Cliente { get; set; }
        public virtual DbSet<TB_Ubigeo> TB_Ubigeo { get; set; }
        public virtual DbSet<TB_Bitacora> TB_Bitacora { get; set; }
        public virtual DbSet<TB_OrdenDespacho> TB_OrdenDespacho { get; set; }
        public virtual DbSet<TB_Producto> TB_Producto { get; set; }
        public virtual DbSet<vw_VistaProducto> vw_VistaProducto { get; set; }
        public virtual DbSet<vw_VistaCliente> vw_VistaCliente { get; set; }
        public virtual DbSet<vw_VistaOrdenDespacho> vw_VistaOrdenDespacho { get; set; }
    
        public virtual int usp_ActualizarCliente(string vcodClie, string idUbig, string tipoCli, string nombClie, string apeClie, string rucClie, string dniClie, string dirClie, string razSocClie, string usuModCli, string estClie)
        {
            var vcodClieParameter = vcodClie != null ?
                new ObjectParameter("vcodClie", vcodClie) :
                new ObjectParameter("vcodClie", typeof(string));
    
            var idUbigParameter = idUbig != null ?
                new ObjectParameter("idUbig", idUbig) :
                new ObjectParameter("idUbig", typeof(string));
    
            var tipoCliParameter = tipoCli != null ?
                new ObjectParameter("tipoCli", tipoCli) :
                new ObjectParameter("tipoCli", typeof(string));
    
            var nombClieParameter = nombClie != null ?
                new ObjectParameter("NombClie", nombClie) :
                new ObjectParameter("NombClie", typeof(string));
    
            var apeClieParameter = apeClie != null ?
                new ObjectParameter("ApeClie", apeClie) :
                new ObjectParameter("ApeClie", typeof(string));
    
            var rucClieParameter = rucClie != null ?
                new ObjectParameter("rucClie", rucClie) :
                new ObjectParameter("rucClie", typeof(string));
    
            var dniClieParameter = dniClie != null ?
                new ObjectParameter("dniClie", dniClie) :
                new ObjectParameter("dniClie", typeof(string));
    
            var dirClieParameter = dirClie != null ?
                new ObjectParameter("dirClie", dirClie) :
                new ObjectParameter("dirClie", typeof(string));
    
            var razSocClieParameter = razSocClie != null ?
                new ObjectParameter("razSocClie", razSocClie) :
                new ObjectParameter("razSocClie", typeof(string));
    
            var usuModCliParameter = usuModCli != null ?
                new ObjectParameter("UsuModCli", usuModCli) :
                new ObjectParameter("UsuModCli", typeof(string));
    
            var estClieParameter = estClie != null ?
                new ObjectParameter("estClie", estClie) :
                new ObjectParameter("estClie", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarCliente", vcodClieParameter, idUbigParameter, tipoCliParameter, nombClieParameter, apeClieParameter, rucClieParameter, dniClieParameter, dirClieParameter, razSocClieParameter, usuModCliParameter, estClieParameter);
        }
    
        public virtual int usp_EliminarCliente(string vcodClie)
        {
            var vcodClieParameter = vcodClie != null ?
                new ObjectParameter("vcodClie", vcodClie) :
                new ObjectParameter("vcodClie", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarCliente", vcodClieParameter);
        }
    
        public virtual int usp_InsertarCliente(string idUbig, string tipoCli, string nombClie, string apeClie, string rucClie, string dniClie, string dirClie, string razSocClie, string usuRegClie, string estClie)
        {
            var idUbigParameter = idUbig != null ?
                new ObjectParameter("idUbig", idUbig) :
                new ObjectParameter("idUbig", typeof(string));
    
            var tipoCliParameter = tipoCli != null ?
                new ObjectParameter("tipoCli", tipoCli) :
                new ObjectParameter("tipoCli", typeof(string));
    
            var nombClieParameter = nombClie != null ?
                new ObjectParameter("NombClie", nombClie) :
                new ObjectParameter("NombClie", typeof(string));
    
            var apeClieParameter = apeClie != null ?
                new ObjectParameter("ApeClie", apeClie) :
                new ObjectParameter("ApeClie", typeof(string));
    
            var rucClieParameter = rucClie != null ?
                new ObjectParameter("rucClie", rucClie) :
                new ObjectParameter("rucClie", typeof(string));
    
            var dniClieParameter = dniClie != null ?
                new ObjectParameter("dniClie", dniClie) :
                new ObjectParameter("dniClie", typeof(string));
    
            var dirClieParameter = dirClie != null ?
                new ObjectParameter("dirClie", dirClie) :
                new ObjectParameter("dirClie", typeof(string));
    
            var razSocClieParameter = razSocClie != null ?
                new ObjectParameter("razSocClie", razSocClie) :
                new ObjectParameter("razSocClie", typeof(string));
    
            var usuRegClieParameter = usuRegClie != null ?
                new ObjectParameter("UsuRegClie", usuRegClie) :
                new ObjectParameter("UsuRegClie", typeof(string));
    
            var estClieParameter = estClie != null ?
                new ObjectParameter("estClie", estClie) :
                new ObjectParameter("estClie", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarCliente", idUbigParameter, tipoCliParameter, nombClieParameter, apeClieParameter, rucClieParameter, dniClieParameter, dirClieParameter, razSocClieParameter, usuRegClieParameter, estClieParameter);
        }
    
        public virtual ObjectResult<usp_ListarCliente_Result> usp_ListarCliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarCliente_Result>("usp_ListarCliente");
        }
    
        public virtual ObjectResult<usp_ProductoMasProducidoXAño_Result> usp_ProductoMasProducidoXAño(Nullable<int> año)
        {
            var añoParameter = año.HasValue ?
                new ObjectParameter("año", año) :
                new ObjectParameter("año", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ProductoMasProducidoXAño_Result>("usp_ProductoMasProducidoXAño", añoParameter);
        }
    
        public virtual ObjectResult<usp_ClienteMasOrdenDespacho_Result> usp_ClienteMasOrdenDespacho()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ClienteMasOrdenDespacho_Result>("usp_ClienteMasOrdenDespacho");
        }
    
        public virtual ObjectResult<usp_CantidadDespachoPorAño_Result> usp_CantidadDespachoPorAño()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CantidadDespachoPorAño_Result>("usp_CantidadDespachoPorAño");
        }
    
        public virtual ObjectResult<usp_DepartamentoMasOrdenDespacho_Result> usp_DepartamentoMasOrdenDespacho()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_DepartamentoMasOrdenDespacho_Result>("usp_DepartamentoMasOrdenDespacho");
        }
    
        public virtual ObjectResult<SpRankingCliente_Result> SpRankingCliente(Nullable<System.DateTime> fec_ini, Nullable<System.DateTime> fec_fin)
        {
            var fec_iniParameter = fec_ini.HasValue ?
                new ObjectParameter("fec_ini", fec_ini) :
                new ObjectParameter("fec_ini", typeof(System.DateTime));
    
            var fec_finParameter = fec_fin.HasValue ?
                new ObjectParameter("fec_fin", fec_fin) :
                new ObjectParameter("fec_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpRankingCliente_Result>("SpRankingCliente", fec_iniParameter, fec_finParameter);
        }
    }
}
