//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Cerveza
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Bitacora
    {
        public string Id_bitacora { get; set; }
        public string Id_empleado { get; set; }
        public string Id_receta { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public int litros_producidos { get; set; }
        public string tiempo_real { get; set; }
        public Nullable<System.DateTime> inicio_fermentacion { get; set; }
        public Nullable<System.DateTime> fin_fermentacion { get; set; }
        public Nullable<System.DateTime> FechaIni_desc { get; set; }
        public Nullable<System.DateTime> InicioMaduracion_frio { get; set; }
        public Nullable<System.DateTime> FinMaduracion_frio { get; set; }
        public Nullable<System.DateTime> Fecha_DryHopp { get; set; }
        public string Peso_fermentadores { get; set; }
        public string id_UnidadMedida { get; set; }
        public Nullable<int> Cantid_Barriles { get; set; }
        public string NotasDelMaestro { get; set; }
        public Nullable<System.DateTime> FechaFin_desc { get; set; }
        public string DryHopp { get; set; }
        public string Id_op { get; set; }
    }
}
