//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Cerveza
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Cliente()
        {
            this.TB_OrdenDespacho = new HashSet<TB_OrdenDespacho>();
        }
    
        public string id_cliente { get; set; }
        public string id_Ubigeo { get; set; }
        public string tipo_cli { get; set; }
        public string nom_cli { get; set; }
        public string ape_cli { get; set; }
        public string ruc_cli { get; set; }
        public string dni_cli { get; set; }
        public string direccion_cli { get; set; }
        public string raz_soc_cli { get; set; }
        public Nullable<System.DateTime> fec_reg_cli { get; set; }
        public string usu_reg_cli { get; set; }
        public Nullable<System.DateTime> fec_ultm_mod_cli { get; set; }
        public string usu_ultm_mod_cli { get; set; }
        public string estado_cli { get; set; }
    
        public virtual TB_Ubigeo TB_Ubigeo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_OrdenDespacho> TB_OrdenDespacho { get; set; }
    }
}
