//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Cerveza
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_OrdenDespacho
    {
        public string id_ord_desp { get; set; }
        public string ID_Producto { get; set; }
        public string id_cliente { get; set; }
        public Nullable<int> cantidad_des { get; set; }
        public string precentacion_des { get; set; }
        public string pto_venta { get; set; }
        public string estado_res { get; set; }
        public Nullable<System.DateTime> fec_reg_des { get; set; }
    
        public virtual TB_Cliente TB_Cliente { get; set; }
        public virtual TB_Producto TB_Producto { get; set; }
    }
}
