//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Cerveza
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VistaProducto
    {
        public string ID_Producto { get; set; }
        public string id_UnidadMedida { get; set; }
        public string Descripcion { get; set; }
        public string tipo_producto { get; set; }
        public string Tipo_de_producto { get; set; }
        public string Presentacion { get; set; }
        public string unidad_nom { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> Stock_min { get; set; }
    }
}
